In [15]:
import random

from luxury_style import LuxurySlideDeck


deck = LuxurySlideDeck()

lecture_4_slides = {

    "intro_mlp": {
    "title": "المحاضرة: مقدّمة في الشبكات العصبية متعددة الطبقات (MLP) 🧠⚡",
    "description": r"""
        <h3>ما هي شبكة الـ MLP؟</h3>

        <p>
            <strong>MLP – Multi-Layer Perceptron</strong> هي أبسط شكل من الشبكات العصبية
            العميقة، وتتكون من عدة طبقات مرتّبة فوق بعضها:
        </p>

        <div style="margin-right: 25px;">
            • طبقة دخل (Input Layer) – تستقبل البيانات الخام.<br>
            • طبقات خفية (Hidden Layers) – تتعلم الأنماط والعلاقات داخل البيانات.<br>
            • طبقة خرج (Output Layer) – تنتج التنبؤ النهائي (تصنيف/احتمالات).<br>
        </div>

        <br>

        <p>
            شبكة MLP تعتبر حجر الأساس لفهم <strong>Deep Learning</strong>،
            وهي النموذج الأول الذي يجب أن يتعلمه الطالب قبل الانتقال إلى
            الشبكات الالتفافية (CNN) أو الشبكات المتقدمة مثل Transformers.
        </p>

        <blockquote>
            "MLP لا ترى الصورة…
            لكنها تفهم الأرقام. لذلك نعلّمها كيف نحول كل شيء إلى أرقام!"
        </blockquote>

        <h3>لماذا نبدأ بـ MLP؟</h3>

        <ul>
            <li>أبسط نموذج لفهم فكرة الطبقات وتدفق المعلومات.</li>
            <li>يعمل بشكل ممتاز على البيانات الجدولية (Tabular Data).</li>
            <li>يمكن استخدامه للصور بعد تحويلها إلى متجهات (Flattening).</li>
            <li>أساس مهم لفهم Backpropagation والتعلّم العميق.</li>
        </ul>

        <p>
            في هذه المحاضرة سنقوم ببناء نموذج MLP بسيط،
            ونجربه على بيانات جدولية أولاً، ثم ننتقل إلى تحدٍ أكبر:
            <strong>تصنيف صور الأرقام الشهيرة MNIST</strong>.
        </p>
    """,

    "steps_data": [
        {
            "title": "ما الذي سنتعلمه اليوم؟",
            "explanation": "سنرى كيف تنتقل البيانات بين الطبقات، وكيف تتعلم الشبكة الأنماط، ثم نطبّق MLP على بيانات جدولية وصور MNIST.",
            "reason": "لفهم الشبكات العميقة، يجب أولاً فهم كيفية بناء أبسط شبكة عصبية متعددة الطبقات."
        }
    ]
}
,

"mlp_tabular": {
    "title": "1. تجربة MLP على بيانات جدولية (Tabular Data) 📊",
    "description": r"""
        <h3>البيانات الجدولية: البيئة الطبيعية للـ MLP</h3>

        <p>
            قبل أن نذهب إلى عالم الصور، سنبدأ بالأساس:
            <strong>البيانات الجدولية</strong>.
            هذا النوع من البيانات هو الأفضل لشرح طريقة عمل الـ MLP، لأن كل عيّنة
            تُختصر في مجموعة من <strong>الخصائص (Features)</strong> الواضحة.
        </p>

        <p>
            سنستخدم مثالاً مشهورًا وهو
            <strong>Iris Dataset</strong>،
            والذي يحتوي على قياسات لزهور Iris وأنواعها المختلفة.
        </p>

        <div class='reason-text'>
            💡 الفكرة الأساسية هنا أن الشبكة تتعلم العلاقة بين القيم الرقمية
            (مثل الطول والعرض) وبين الفئة التي تنتمي لها العينة.
        </div>

        <h3>لماذا نستخدم بيانات جدولية أولاً؟</h3>

        <ul>
            <li>لفهم آلية عمل الطبقات العصبية دون تعقيد الصور.</li>
            <li>لأن المدخلات جاهزة ومسطّحة (لا تحتاج Flatten).</li>
            <li>لرؤية تأثير عدد الطبقات وعدد النيرونات بشكل مباشر.</li>
        </ul>

        <blockquote>
            "إذا فهمت كيف يتعامل MLP مع 4 فيتشرات…
            ستفهم كيف يتعامل مع 784 فيتشر في MNIST."
        </blockquote>
    """,

    "steps_data": [
        {
            "title": "تحميل البيانات وتجهيزها",
            "explanation": "قراءة بيانات Iris وتقسيمها إلى Train و Test.",
            "reason": "تهيئة البيانات هي الخطوة الأولى قبل بناء أي نموذج."
        },
        {
            "title": "بناء نموذج MLP بسيط",
            "explanation": "طبقة دخل → طبقة خفية بـ ReLU → طبقة خرج بعدد الفئات.",
            "reason": "لتعلّم الفكرة الأساسية للشبكات العصبية."
        },
        {
            "title": "تدريب النموذج وتقييمه",
            "explanation": "نراقب الدقة ونفهم كيف يتعلم النموذج من الخصائص الرقمية.",
            "reason": "لإظهار كيف يعمل الـ MLP في أفضل بيئته."
        }
    ]
},
    "mlp_images_intro": {
    "title": "2. لماذا التعامل مع الصور مختلف عن البيانات الجدولية؟ 🖼️➡️📊",
    "description": r"""
        <h3>من جدول أرقام إلى شبكة بكسلات</h3>

        <p>
            في بيانات Iris، كل عيّنة كانت مجرد <strong>4 أرقام</strong> تمثل أطوال وعروض الأزهار.
            هذا شكل طبيعي جداً لتغذيته إلى شبكة MLP:
        </p>

        <div style="margin-right: 25px;">
            <code>[ sepal_length, sepal_width, petal_length, petal_width ]</code>
        </div>

        <p>
            لكن مع الصور، الوضع مختلف تمامًا… فالصورة ليست مجرد رقمين أو ثلاثة،
            بل هي <strong>مصفوفة ثنائية الأبعاد</strong> من البكسلات.
        </p>

        <h3>مثال: صور MNIST</h3>
        <p>
            صور MNIST هي صور أرقام مكتوبة باليد بحجم:
        </p>
        <div style="margin-right: 25px;">
            <strong>28 × 28 بكسل</strong> لكل صورة ⟵ أي <strong>784 قيمة</strong> لكل صورة.
        </div>

        <p>
            أي صورة من MNIST يمكن تمثيلها كمصفوفة:
        </p>

        <pre>
        [ p11 p12 p13 ... p1,28
          p21 p22 p23 ... p2,28
          ...
          p28,1 ...       p28,28 ]
        </pre>

        <h3>المشكلة مع MLP:</h3>
        <ul>
            <li>طبقة الـ MLP تتوقع <strong>متجهًا (Vector)</strong> من الأرقام، وليس مصفوفة 2D.</li>
            <li>لا تعرف أن هذه الأرقام مرتبة على شكل صورة.</li>
            <li>كل ما تراه هو "قائمة طويلة من الأعداد".</li>
        </ul>

        <blockquote>
            "بالنسبة لـ MLP… الصورة ليست صورة، بل مجرد 784 رقمًا مصفوفة خلف بعضها."
        </blockquote>

        <h3>الحل: عملية Flatten</h3>
        <p>
            قبل أن ندخل الصورة إلى شبكة MLP، نقوم بتحويلها من مصفوفة 28×28 إلى
            <strong>متجه واحد طوله 784</strong>:
        </p>

        <div style="margin-right: 25px;">
            <code>(28, 28) ⟶ (784,)</code>
        </div>

        <p>
            بهذه الطريقة تصبح الصورة <strong>بيانات جدولية الشكل</strong>، ويمكن لـ MLP التعامل معها
            كما لو كانت مجرد 784 خاصية (Feature) مثل أي جدول أرقام آخر.
        </p>

        <div class='reason-text'>
            💡 هذه الفكرة مهمة جدًا:<br>
            <strong>نحن لا نغيّر النموذج… بل نغيّر شكل البيانات لتناسب النموذج.</strong>
        </div>
    """,

    "steps_data": [
        {
            "title": "فهم أبعاد الصورة",
            "explanation": "صورة MNIST هي مصفوفة 28×28 من قيم البكسل، وليست مجرد صف واحد من الأرقام.",
            "reason": "لفهم لماذا لا يمكن إدخال الصورة مباشرة إلى طبقة Dense."
        },
        {
            "title": "تحويل الصورة إلى متجه (Flatten)",
            "explanation": "نقوم بفرد مصفوفة البكسلات إلى متجه بطول 784 قيمة.",
            "reason": "حتى تصبح الصورة في شكل يناسب طبقة الدخل في شبكة MLP."
        },
        {
            "title": "التمهيد لـ CNN مستقبلاً",
            "explanation": "MLP يعامل الصورة كأرقام فقط، بينما CNN تحفظ البنية المكانية للصورة.",
            "reason": "لبناء جسر مفاهيمي يمهد للانتقال لاحقًا إلى الشبكات الالتفافية."
        }
    ]
},"mnist_overview": {
    "title": "3. التعرّف على بيانات MNIST – أشهر بيانات في الذكاء الاصطناعي 🖼️🔢",
    "description": r"""
        <h3>ما هي بيانات MNIST؟</h3>

        <p>
            MNIST هي مجموعة صور لأرقام مكتوبة بخط اليد، تم التقاطها من آلاف الأشخاص.
            وتعد من أشهر البيانات المستخدمة في التدريب على خوارزميات
            <strong>Deep Learning</strong>، لأنها بسيطة ومثالية للمبتدئين.
        </p>

        <ul>
            <li>عدد الصور: 70,000 صورة.</li>
            <li>حجم كل صورة: <strong>28 × 28 بكسل</strong>.</li>
            <li>الألوان: تدرّج الرمادي (Grayscale) — يعني قيمة واحدة لكل بكسل.</li>
            <li>عدد الفئات: <strong>10 أرقام (0–9)</strong>.</li>
        </ul>

        <h3>شكل الصورة قبل المعالجة:</h3>

        <pre>
        (28 × 28) ⟵ مصفوفة من قيم البكسل (0–255)
        </pre>

        <h3>شكل الصورة بعد Flatten:</h3>

        <pre>
        (784,) ⟵ متجه طويل يصلح للدخول إلى شبكة MLP
        </pre>

        <blockquote>
            "الصورة هي مجرد رقم… إذا قمت بفردها."
        </blockquote>

        <h3>لماذا MNIST مثالية للتعلم؟</h3>

        <ul>
            <li>صور صغيرة وسهلة المعالجة.</li>
            <li>لا تحتاج إلى GPU لتدريب النماذج.</li>
            <li>مناسبة لتعليم MLP و CNN.</li>
            <li>تشرح المفهوم الأساسي لتصنيف الصور بشكل ممتاز.</li>
        </ul>

        <div class='reason-text'>
            💡 قبل بناء MLP، يجب تجهيز البيانات: التطبيع (Normalization) + تحويل الشكل (Flatten).
        </div>
    """,

    "steps_data": [
        {
            "title": "تحميل بيانات MNIST",
            "explanation": "نستخدم الداتا الجاهزة داخل Keras لسهولة الاستخدام.",
            "reason": "Keras توفر طريقة مباشرة وسريعة لتحميل البيانات دون الحاجة لأي ملفات خارجية."
        },
        {
            "title": "تطبيع البيانات",
            "explanation": "نحوّل قيم البكسل من 0–255 إلى قيم بين 0 و 1.",
            "reason": "تسريع التدريب ومنع الشبكة من الاختناق بقيم كبيرة."
        },
        {
            "title": "تحويل الشكل (Flatten)",
            "explanation": "تحويل الصورة من (28, 28) إلى (784,) باستخدام reshape.",
            "reason": "MLP يحتاج مدخلات أحادية البعد فقط."
        }
    ]
}
,
    "mnist_mlp_build": {
    "title": "4. بناء شبكة MLP لتصنيف أرقام MNIST 🧠🔢",
    "description": r"""
        <h3>من 784 رقمًا إلى قرار واحد: أي رقم هذا؟</h3>

        <p>
            بعد أن جهزنا بيانات MNIST (تطبيع + Flatten)، حان وقت بناء
            <strong>شبكة عصبية متعددة الطبقات (MLP)</strong> لتتعلم كيف تميّز بين الأرقام (0–9).
        </p>

        <p>
            كل صورة الآن تمثّل كـ <strong>متجه يحتوي 784 قيمة</strong> (قيمة لكل بكسل)،
            وهي تدخل إلى طبقة الدخل في الشبكة، ثم تمر عبر عدة طبقات خفية،
            وفي النهاية نخرج <strong>10 احتمالات</strong> تمثل الأرقام من 0 إلى 9.
        </p>

        <h3>هيكلية شبكة الـ MLP لـ MNIST:</h3>

        <ul>
            <li><strong>طبقة الدخل (Input Layer):</strong> حجمها 784، واحدة لكل بكسل.</li>
            <li><strong>طبقات خفية (Hidden Layers):</strong>
                طبقتان أو أكثر من نوع <code>Dense</code> مع <code>ReLU</code> لتعلّم الأنماط.</li>
            <li><strong>طبقة خرج (Output Layer):</strong>
                عدد النيورونات = 10، مع <code>Softmax</code> لإعطاء احتمال لكل رقم.</li>
        </ul>

        <h3>دوال التنشيط المستخدمة:</h3>
        <ul>
            <li><strong>ReLU (Rectified Linear Unit):</strong>
                دالة تنشيط غير خطية تستخدم في الطبقات الخفية،
                تساعد الشبكة على تعلّم علاقات معقدة ولا تعاني كثيرًا من مشكلة تلاشي المشتقات.</li>
            <li><strong>Softmax:</strong>
                دالة تنشيط في طبقة الخرج، تحوّل الأرقام الخام (logits) إلى
                <strong>توزيع احتمالي</strong> مجموع قيمه = 1 على الفئات العشر.</li>
        </ul>

        <blockquote>
            "كل صورة تمر عبر عدّة طبقات من التحويلات…
            وفي النهاية الشبكة تقول: &nbsp;أغلب الظن أنه الرقم 7 بنسبة 0.93."
        </blockquote>

        <h3>اختيارات تصميمية (Hyperparameters):</h3>
        <ul>
            <li><strong>عدد النيورونات في الطبقات الخفية:</strong> مثلاً 128 ثم 64.</li>
            <li><strong>دالة الخسارة (Loss):</strong> نستخدم <code>categorical_crossentropy</code>.</li>
            <li><strong>المُحسِّن (Optimizer):</strong> نستخدم <code>Adam</code> كبداية قوية.</li>
            <li><strong>المؤشر (Metric):</strong> نستخدم <code>accuracy</code> لقياس الأداء.</li>
        </ul>

        <div class='reason-text'>
            💡 هذه الشبكة ليست الأقوى للصور (CNN أفضل)، لكنها ممتازة لفهم فكرة
            <strong>الطبقات، والتعلّم التدريجي، وكيف تتحول الأرقام إلى قرار تصنيفي.</strong>
        </div>
    """,

    "steps_data": [
        {
            "title": "تحديد شكل الدخل (Input Shape)",
            "explanation": "نستخدم 784 كحجم للدخل لأن كل صورة تم فردها إلى متجه بطول 784.",
            "reason": "كل نيوترون في طبقة الدخل يستقبل قيمة بكسل واحدة."
        },
        {
            "title": "إضافة طبقات خفية مع ReLU",
            "explanation": "نستخدم طبقتين مثل 128 و 64 نيوترون مع ReLU لاكتشاف الأنماط داخل الصور.",
            "reason": "كل طبقة تتعلم مستوى أعمق من التمثيل: من بكسلات → أشكال → أرقام."
        },
        {
            "title": "طبقة خرج مع Softmax",
            "explanation": "نضيف 10 نيوترونات، واحد لكل رقم، مع Softmax لإنتاج توزيع احتمالي على الفئات.",
            "reason": "لنتمكن من قول: هذه الصورة هي '3' بنسبة 97% مثلاً."
        }
    ]
}
,
    "mlp_summary": {
    "title": "5. الملخص النهائي: ماذا تعلمنا اليوم؟ 🧠✨",
    "description": r"""
        <h3>رحلة كاملة من البيانات الجدولية إلى الصور</h3>

        <p>
            خلال هذه المحاضرة، انتقلنا تدريجيًا من الأساسيات إلى بناء نموذج MLP
            قادر على تصنيف الأرقام المكتوبة بخط اليد (MNIST).
            كانت الرحلة تهدف إلى فهم <strong>كيف تتعلم الشبكة العصبية</strong>
            وكيف نتعامل مع أنواع مختلفة من البيانات.
        </p>

        <h3>أهم ما تعلمناه:</h3>
        <ul>
            <li><strong>MLP</strong> هو أبسط نموذج من نماذج الشبكات العصبية العميقة.</li>
            <li>يعمل بشكل ممتاز على <strong>البيانات الجدولية</strong> مثل Iris.</li>
            <li>الصور ليست جدولية، لذلك نحتاج <strong>Flatten</strong> لتحويلها إلى متجه.</li>
            <li>MNIST يعتبر أفضل مثال تعليمي لتصنيف الصور.</li>
            <li>الطبقات الخفية مع <code>ReLU</code> تتعلم تمثيلات معقدة.</li>
            <li>طبقة <strong>Softmax</strong> ضرورية للتصنيف متعدد الفئات (0–9).</li>
            <li>مفهوم <strong>Loss / Accuracy</strong> هو قلب عملية التدريب.</li>
        </ul>

        <blockquote>
            "الشبكة العصبية لا ترى صورة… بل ترى أرقاماً.
            ونحن نعلمها كيف تربط هذه الأرقام بمعنى أو قرار."
        </blockquote>

        <h3>ماذا بعد MLP؟</h3>
        <ul>
            <li>للصور: الانتقال الطبيعي هو <strong>CNN – Convolutional Neural Networks</strong>.</li>
            <li>للنصوص: الانتقال إلى <strong>RNN – LSTM – Transformers</strong>.</li>
            <li>للتمثيل المتقدم: استخدام <strong>Autoencoders</strong> و <strong>GANs</strong>.</li>
        </ul>

        <p>
            أصبحت الآن تمتلك الأساس القوي لبناء شبكات عصبية ومعالجة صور MNIST،
            وهذا يمهّد الطريق للدخول إلى عالم أعمق من التعلم العميق!
        </p>
    """,

    "steps_data": [
        {
            "title": "من البيانات الجدولية إلى الصور",
            "explanation": "رأينا كيف أن MLP مناسب طبيعيًا للبيانات الجدولية، وكيف يمكن تهيئة الصور لتصبح مناسبة أيضًا.",
            "reason": "لفهم التحويلات التي نطبقها على البيانات قبل إدخالها إلى الشبكة."
        },
        {
            "title": "دور الطبقات الخفية",
            "explanation": "كل طبقة تتعلم مستوى أعلى من الأنماط داخل البيانات.",
            "reason": "هذا هو جوهر التعلم العميق."
        },
        {
            "title": "توقعات النموذج",
            "explanation": "الشبكة تنتج توزيع احتمالات يمثل ثقتها بكل فئة.",
            "reason": "لفهم كيف يتخذ النموذج قرار التصنيف."
        }
    ]
}




}

deck.show(lecture_4_slides['intro_mlp'])

In [2]:
deck.show(lecture_4_slides['mlp_tabular'])


In [3]:
# pip install scikit-learn tensorflow numpy
# pip list


# ==============================
# 1) تحميل وتجهيز بيانات Iris
# ==============================
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.utils import to_categorical
import numpy as np
import random
# تحميل الداتا
iris = load_iris()
X = iris.data          # الخصائص (4 أعمدة: طول/عرض السبلات والبتلات)
# print(type(X))
# 1) طول الكأس (Sepal Length)
# 2) عرض الكأس (Sepal Width)
# 3) طول البتلة (Petal Length)
# 4) عرض البتلة (Petal Width)
#
# وكلها مقاسة بالسنتيمتر.
y = iris.target        # الليبلات (0, 1, 2) لأن لدينا 3 أنواع زهور
# print(y.shape)
# ----------------------- ملخص أنواع زهور Iris -----------------------
# لدينا ثلاثة أنواع رئيسية في iris.target:
#
# 0 → Iris Setosa
#     - أصغر الأنواع
#     - بتلات قصيرة جداً (Petal Length ~ 1 سم)
#     - لونها أفتح وغالباً بنفسجي فاتح
#
# 1 → Iris Versicolor
#     - حجم متوسط
#     - بتلات أطول قليلاً (Petal Length ~ 4 سم)
#     - لون بنفسجي أعمق مع خطوط صفراء
#
# 2 → Iris Virginica
#     - أكبر الأنواع الثلاثة
#     - بتلات طويلة وعريضة (Petal Length ~ 5–6 سم)
#     - لون بنفسجي غامق وواضح
#
# هذه الأنواع هي الهدف (Labels) المستخدمة في نماذج تصنيف Iris.
# --------------------------------------------------------------------


print("شكل X:", X.shape)
print("شكل y:", y.shape)
print("أسماء الفئات:", iris.target_names)
# #
# # # تقسيم إلى تدريب واختبار
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
# #
# # # توحيد القيم (Standardization) لتحسين التدريب
scaler = StandardScaler()
# print(X_train[0])
X_train = scaler.fit_transform(X_train)
# print(X_train[0])
# print(X_test[0])
X_test = scaler.transform(X_test)
# print(X_test[0])
# مثال على طريقة عمل StandardScaler:
#
# لدينا القيم:
# [10, 12, 14]
#
# المتوسط = 12
# الانحراف المعياري ≈ 1.63
#
# بعد تطبيق StandardScaler تصبح القيم:
# (10 − 12) ÷ 1.63 ≈ -1.22
# (12 − 12) ÷ 1.63 = 0
# (14 − 12) ÷ 1.63 ≈ +1.22
#
# الملاحظة:
# - القيم الأقل من المتوسط → تتحول إلى أرقام سالبة
# - القيمة عند المتوسط → تصبح 0
# - القيم الأكبر من المتوسط → تتحول إلى أرقام موجبة
#
# الهدف من العملية:
# جعل القيم موزونة وموزعة حول الصفر لتسهيل تعلم النموذج.

#
# # تحويل الليبلات إلى one-hot (لأننا بنستخدم Softmax)
# تحويل الليبلات إلى One-Hot Encoding:
# أولاً نحدد عدد الفئات الموجودة في البيانات، مثلاً: [0, 1, 2] → 3 فئات.
num_classes = len(np.unique(y))
# print(num_classes)
# # to_categorical يقوم بتحويل كل ليبل من رقم واحد إلى متجه احتمالات،
# # مثل: 2 → [0, 0, 1]
# # هذا الشكل هو الذي تفهمه طبقة softmax وتتعامل معه دالة الخسارة.
print(y_train)
y_train_cat = to_categorical(y_train, num_classes=num_classes)
print("*"*50)
print(y_train_cat)
y_test_cat = to_categorical(y_test, num_classes=num_classes)
print("*"*50)
print(y_test_cat)



2025-12-07 11:01:05.791635: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2025-12-07 11:01:05.985609: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-12-07 11:01:10.712796: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.


شكل X: (150, 4)
شكل y: (150,)
أسماء الفئات: ['setosa' 'versicolor' 'virginica']
[0 2 1 0 1 2 1 2 2 2 2 1 1 1 1 0 0 2 2 0 1 0 2 0 1 2 2 0 2 0 0 1 1 0 2 2 1
 1 2 1 0 1 0 2 0 0 2 0 0 0 0 1 2 1 0 2 1 2 0 2 0 1 2 0 1 1 2 1 1 2 0 0 0 2
 1 2 1 2 2 1 0 2 1 0 2 0 2 1 1 0 1 2 0 0 2 2 2 1 2 0 2 1 2 2 0 1 1 1 1 1 0
 2 1 1 0 0 0 0 1 0]
**************************************************
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]


In [4]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
# ==============================
# 2) بناء نموذج MLP بسيط
# ==============================
mlp_tabular_model = Sequential()

print(X_train.shape[1])
# طبقة الدخل: عدد النيورونات = عدد الخصائص (4 في Iris)
mlp_tabular_model.add(Input(shape=(X_train.shape[1],)))
# #
# # # طبقة خفية أولى
mlp_tabular_model.add(Dense(16, activation='relu'))
# #
# # Dense Layer (Fully Connected):
# # طبقة تحتوي على عدد من النيورنات، كل نيورون متصل بجميع مخرجات الطبقة السابقة.
# # كل نيورون يقوم بعملية: (Wx + b) ثم يطبق دالة التفعيل للحصول على المخرجات.
# # تستخدم لتعلّم الأنماط والعلاقات داخل البيانات، ومخرجاتها تكون متجه بطول عدد النيورنات.
#
#   # x1 ----\
#   # x2 -----\__  [Neuron 1]
#   # x3 -----/
#   # x4 ----/
#   #
#   # x1 ----\
#   # x2 -----\__  [Neuron 2]
#   # x3 -----/
#   # x4 ----/
#   #
#   # x1 ----\
#   # x2 -----\__  [Neuron 3]
#   # x3 -----/
#   # x4 ----/
# # ReLU (Rectified Linear Unit):
# # دالة تفعيل تجعل القيم السالبة = 0 وتُبقي القيم الموجبة كما هي.
# # تعطي الشبكة قدرة على تعلم علاقات لاخطية، وتساعد في تسريع التدريب
# # وتخفيف مشكلة تلاشي التدرج (Vanishing Gradient).
# # تُستخدم غالباً في الطبقات الخفية لأنها بسيطة وسريعة وفعّالة.
#
# # # طبقة خفية ثانية (اختيارية لكنها تساعد النموذج)
mlp_tabular_model.add(Dense(8, activation='relu'))
# #
# # # طبقة الخرج: عدد النيورونات = عدد الفئات (3)، مع Softmax للتصنيف المتعدد
mlp_tabular_model.add(Dense(num_classes, activation='softmax'))
# # Softmax: دالة تفعيل تحول مخرجات الطبقة إلى احتمالات مجموعها = 1،
# # تستخدم للتصنيف متعدد الفئات لأنها تختار الفئة الأرجح بناءً على أعلى احتمال.



4


E0000 00:00:1765094473.610630   41126 cuda_executor.cc:1309] INTERNAL: CUDA Runtime error: Failed call to cudaGetRuntimeVersion: Error loading CUDA libraries. GPU will not be used.: Error loading CUDA libraries. GPU will not be used.
W0000 00:00:1765094473.622450   41126 gpu_device.cc:2342] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [5]:

# ==============================
# 3) تجميع (Compile) النموذج
# ==============================
# compile:جهّز النموذج ليبدأ التدريب. أربطه بخوارزمية تدريب ودالة خسارة وطريقة قياس.

# Adam Optimizer (محسّن آدم):
# خوارزمية تدريب ذكية تجمع بين ميزتي Momentum (الزخم)
# و RMSProp (تعديل معدل التعلّم حسب حجم التغيّر)،
# فتتبع متوسط واتجاه الـ gradients (مشتقات الخسارة) عبر الزمن،
# وتضبط حجم خطوة التعلّم لكل وزن بشكل تكيفي،
# مما يجعل عملية التدريب أسرع وأكثر استقرارًا مقارنة بالطرق التقليدية.
# categorical_crossentropy:
# دالة خسارة تُستخدم في التصنيف متعدد الفئات، وظيفتها قياس مدى دقة النموذج
mlp_tabular_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',   # لأننا نستخدم one-hot labels
    metrics=['accuracy']
)

mlp_tabular_model.summary()

# ==============================
# 4) تدريب النموذج
# ==============================
history = mlp_tabular_model.fit(
    X_train,
    y_train_cat,
    epochs=10,
    batch_size=16,
    validation_split=0.2,
    verbose=1  # خليه 1 لو حابب تشوف كل Epoch
)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │            80 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 3)              │            27 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 243 (972.00 B)

 Trainable params: 243 (972.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 5s 224ms/step - accuracy: 0.3333 - loss: 1.1386 - val_accuracy: 0.2500 - val_loss: 1.0839
Epoch 2/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.3542 - loss: 1.0912 - val_accuracy: 0.2917 - val_loss: 1.0453
Epoch 3/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.3646 - loss: 1.0485 - val_accuracy: 0.2500 - val_loss: 1.0102
Epoch 4/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.3542 - loss: 1.0094 - val_accuracy: 0.2500 - val_loss: 0.9783
Epoch 5/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.3542 - loss: 0.9736 - val_accuracy: 0.2500 - val_loss: 0.9513
Epoch 6/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.3646 - loss: 0.9420 - val_accuracy: 0.2500 - val_loss: 0.9257
Epoch 7/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.3646 - loss: 0.9141 - val_accuracy: 0.2917 - val_loss: 0.9022
Epoch 8/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.3750 - loss: 0.8875 - val_accuracy: 0.2917 - val_loss: 0.8803

In [6]:

# ==============================
# 5) تقييم النموذج على بيانات الاختبار
# ==============================
# test_loss, test_acc = mlp_tabular_model.evaluate(X_test, y_test_cat, verbose=1)
# print(f"دقة النموذج على بيانات الاختبار: {test_acc:.3f}")

# ==============================
# 6) تجربة تنبؤ على عينة من البيانات
# ==============================
sample_idx = 0
sample_x = X_test[sample_idx].reshape(1, -1)
sample_true = y_test[sample_idx]
print(sample_true)
print(iris.target_names)
#
# pred_probs = mlp_tabular_model.predict(sample_x)
# print(pred_probs)
# pred_class = np.argmax(pred_probs, axis=1)[0]
# #
# print("\nتجربة عملية:")
# print("القيم المدخلة (features):", sample_x)
# print("الفئة الحقيقية:", iris.target_names[sample_true])
# print("الفئة المتوقعة:", iris.target_names[pred_class])

0
['setosa' 'versicolor' 'virginica']
